name: escala
description: APP para a geração e compartilhamento de escalas de trabalho.
publish_to: 'none'
version: 0.2.2+50

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter    

  teb_package:
    git:
      url: https://github.com/marcosmhs/teb_package.git
      #ref: main
    #path: ../teb_package   

  build_runner: ^2.4.6
  json_theme: ^4.0.0
  intl: ^0.18.1
  flutter_localization: ^0.1.13
  provider: ^6.0.3
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.8.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.2
  firebase_database: ^10.2.5
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0    
  hive_generator: ^1.1.3 # needed for HIVE
  universal_html: ^2.2.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/schedule_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/theme_light.json  
    - assets/theme_dark.json  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
